### ISSUE TITLE
bug(core): Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by yngvebn** [angular/router#225]
Version 0.5.3 installed with Bower

With the most basic setup the new router fails:

    TypeError: Cannot read property 'path' of undefined
        at serializeInstruction (http://localhost:5000/js/vendor.js:42237:24)
        at Object.router.registerViewport.activate (http://localhost:5000/js/vendor.js:42191:31)
        at http://localhost:5000/js/vendor.js:42742:21
        at http://localhost:5000/js/vendor.js:42811:26
        at Array.forEach (native)
        at mapObj (http://localhost:5000/js/vendor.js:42810:22)
        at mapObjAsync (http://localhost:5000/js/vendor.js:42806:19)
        at ChildRouter.queryViewports (http://localhost:5000/js/vendor.js:42763:14)
        at ChildRouter.activatePorts (http://localhost:5000/js/vendor.js:42741:19)
        at http://localhost:5000/js/vendor.js:42745:37

**index.html**

    <body ng-app="demo">
        <div ng-viewport>
        </div>	
    </body>
**demo.module.js**
    angular.module('demo.views', ['demo.views.main'])
    angular.module('Templates', []);
    angular.module('demo', [
        'ngNewRouter',
        'Templates', 
        'demo.views']);
**demo.routes.js**
    function RegisterRoutes($router){
        var routes = [
	        { path: '/', 	component: 'main' }		
        ];

        $router.config(routes);
    }
    angular.module('demo').run(RegisterRoutes);

**MainController**
    function Main(){
    }

    angular.module('demo.views.main')
                .controller('MainController', Main);

This is probably related to #193, but since it is essentially rendering the router useless I'm filing a new bug.

**Comment by yngvebn** [comment]
the example "hello" does not work either, after doing a clean git clone, npm install, gulp and navigating to the example.

Same error
