### ISSUE TITLE
Karma test issue

### ISSUE THREAD

**Issue by Simon-Li** [angular/router#299]
Wondering whether simply run the following would not be able to pass a test run? All the codes are latest cloned, or this needs some configuration tweaks to make it work? but no any guide documentation. If even a simple round of test can be done, I would write a guide note of how this works for newbies.

-------------------------------------------------------------------------------------
[root@vm angular-router]# karma start karma.es5.conf.js
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [Chrome 42.0.2311 (Windows 7)]: Connected on socket PZg22_Bz6iGC9ExdF8fK with id manual-5713
Chrome 42.0.2311 (Windows 7) $componentMapper should convert a component name to a controller name FAILED
        Error: [$injector:unpr] Unknown provider: $componentMapperProvider <- $componentMapper
        http://errors.angularjs.org/1.3.15/$injector/unpr?p0=%24componentMapperProvider%20%3C-%20%24componentMapper
            at /opt/playG/angular-router/node_modules/angular/angular.js:63:12
            at /opt/playG/angular-router/node_modules/angular/angular.js:4015:19
            at Object.getService [as get] (/opt/playG/angular-router/node_modules/angular/angular.js:4162:39)
            at /opt/playG/angular-router/node_modules/angular/angular.js:4020:45
            at getService (/opt/playG/angular-router/node_modules/angular/angular.js:4162:39)
            at Object.invoke (/opt/playG/angular-router/node_modules/angular/angular.js:4194:13)
            at Object.workFn (/opt/playG/angular-router/node_modules/angular-mocks/angular-mocks.js:2436:20)
        Error: Declaration Location
            at window.inject.angular.mock.inject (/opt/playG/angular-router/node_modules/angular-mocks/angular-mock407:25)
            at Suite.<anonymous> (/opt/playG/angular-router/test/component-mapper.es5.spec.js:15:62)
            at /opt/playG/angular-router/test/component-mapper.es5.spec.js:1:1
Chrome 42.0.2311 (Windows 7) $componentMapper should convert a controller name to a component name FAILED
        Error: [$injector:unpr] Unknown provider: $componentMapperProvider <- $componentMapper
        http://errors.angularjs.org/1.3.15/$injector/unpr?p0=%24componentMapperProvider%20%3C-%20%24componentMapper
            at /opt/playG/angular-router/node_modules/angular/angular.js:63:12
            at /opt/playG/angular-router/node_modules/angular/angular.js:4015:19
            at Object.getService [as get] (/opt/playG/angular-router/node_modules/angular/angular.js:4162:39)
            at /opt/playG/angular-router/node_modules/angular/angular.js:4020:45
            at getService (/opt/playG/angular-router/node_modules/angular/angular.js:4162:39)
            at Object.invoke (/opt/playG/angular-router/node_modules/angular/angular.js:4194:13)
            at Object.workFn (/opt/playG/angular-router/node_modules/angular-mocks/angular-mocks.js:2436:20)
        Error: Declaration Location
            at window.inject.angular.mock.inject (/opt/playG/angular-router/node_modules/angular-mocks/angular-mock407:25)
            at Suite.<anonymous> (/opt/playG/angular-router/test/component-mapper.es5.spec.js:19:62)
            at /opt/playG/angular-router/test/component-mapper.es5.spec.js:1:1

**Comment by btford** [comment]
See https://github.com/angular/router/blob/master/CONTRIBUTING.md#setup

**Comment by Simon-Li** [comment]
@btford works perfect, thanks!
