### ISSUE TITLE
Test failed on 'ngOutlet should not reactivate a parent when navigating between child components with different parameters'

### ISSUE THREAD

**Issue by Simon-Li** [angular/router#300]
@btford looks there is a bug in the following line that caused the test failed as shown blow. Just fixed it, may I create a pull request for it?

registerComponent('parent', 'parent { <ng-outlet></ng-outlet> }', ParentController);

---------------------------------------------------------------------------------------
Chrome 42.0.2311 (Mac OS X 10.10.0) ngOutlet should not reactivate a parent when navigating between child components with different parameters FAILED
	TypeError: Cannot read property 'canonicalUrl' of undefined
	    at Grammar.recognize (/opt/angular-router/dist/router.es5.js:1491:93)
	    at RootRouter.recognize (/opt/angular-router/dist/router.es5.js:790:28)
	    at RootRouter.navigate (/opt/angular-router/dist/router.es5.js:718:30)
	    at RootRouter.$$rootRouter.navigate (/opt/angular-router/dist/router.es5.js:104:16)
	    at Object.<anonymous> (/opt/angular-router/test/router-viewport.es5.spec.js:95:13)
Chrome 42.0.2311 (Mac OS X 10.10.0): Executed 44 of 44 (1 FAILED) (2.263 secs / 2.247 secs)

**Comment by nikaspran** [comment]
This is fixed in #298

**Comment by Simon-Li** [comment]
Yeap, close it.
